import re
from typing import Optional
import streamlit as st


def sanitize_markdown_text(text: str) -> str:
    r"""Escape currency dollar signs in markdown strings to prevent KaTeX math mode corruption.

    In Streamlit, multiple unescaped '$' symbols cause text to be rendered as LaTeX math formulas,
    stripping whitespace and italicizing characters. Escaping as r'\$' forces standard text rendering.

    Args:
        text: Input markdown text.

    Returns:
        Sanitized markdown text with escaped dollar signs.
    """
    if not text:
        return text
    # Escape any '$' that is not already preceded by a backslash
    return re.sub(r"(?<!\\)\$", r"\$", text)


def render_data_dictionary_expander() -> None:
    """Render a formal Data Dictionary & Financial Accounting Methodology expander."""
    with st.expander("Data Dictionary — What Each Column Means", expanded=False):
        st.markdown(
            r"""
            ### What's in the Dataset? (51,290 Orders across 147 Countries, 2011–2014)
            | Column | What It Represents |
            | :--- | :--- |
            | **Order ID** | A unique code for each customer order. One order can contain multiple products. |
            | **Order Date** | The date the customer placed the order (2011–2014). |
            | **Ship Date** | The date the order was actually sent out from the warehouse. |
            | **Ship Mode** | How fast the order was delivered: *Same Day*, *First Class* (fast), *Second Class*, or *Standard Class* (slowest, cheapest). |
            | **Customer ID / Name** | Who bought — each customer has a unique ID and name. |
            | **Segment** | What type of buyer: *Consumer* (everyday shoppers), *Corporate* (businesses), or *Home Office* (small offices/freelancers). |
            | **City / State / Country** | Where the order was delivered, across 147 countries. |
            | **Market / Region** | The broad geographic area: *APAC* (Asia-Pacific), *EU* (Europe), *US*, *LATAM* (Latin America), *EMEA* (Middle East & Africa), *Africa*, or *Canada*. |
            | **Product ID / Name** | The specific product that was sold. |
            | **Category** | The product's main group: *Technology*, *Furniture*, or *Office Supplies*. |
            | **Sub-Category** | A finer product group within the main category (e.g. *Phones*, *Chairs*, *Tables*, *Binders*). |
            | **Sales** | The amount the customer was charged (in USD), before any returns. |
            | **Quantity** | How many units were in the order. |
            | **Discount** | The price reduction given to the customer, as a decimal (e.g. 0.20 = 20% off). Range: 0% to 85%. |
            | **Profit** | How much money the company actually made on the order, after subtracting product cost and shipping. A negative number means the company lost money on that sale. |
            | **Shipping Cost** | What it cost to physically deliver the order. |
            | **Order Priority** | How urgently the order needed to be processed: *Critical*, *High*, *Medium*, or *Low*. |

            ---

            ### Key Metrics Used in This Dashboard
            * **Profit Margin (%)** — What percentage of each dollar of sales turns into profit.
              - Formula: `Profit ÷ Sales × 100`. A healthy benchmark is **12% to 15%**.
            * **Loss Drag** — The total money lost from orders that were sold at a loss (i.e., where Profit < 0).
              - In this dataset: **\$920,646** was lost across 12,544 unprofitable orders.
            * **Profitable Contribution** — The total profit generated by all the orders that *did* make money.
              - In this dataset: **\$2,388,103** — but \$920K of that was wiped out by the loss-making orders.
            * **Shipping Cost Ratio (%)** — What percentage of the sale price went to covering delivery costs.
              - Formula: `Shipping Cost ÷ Sales × 100`. When this is above 15% on a discounted order, the company is almost certainly losing money.
            * **The 20% Discount Breaking Point** — Orders with discounts below 20% are profitable (margins of +10% to +25%). Once discounts exceed 20%, the company starts losing money on every item shipped.
            """
        )


def render_chart_story_card(
    title: str,
    what_it_shows: str,
    key_takeaway: str,
    business_impact: str,
    recommendation: Optional[str] = None,
) -> None:
    """Render a formal management consulting interpretation card paired with a visualization.

    Args:
        title: Title of the analytical section.
        what_it_shows: Technical explanation of metrics and parameters.
        key_takeaway: Core empirical variance or pattern identified.
        business_impact: Commercial risk, cost exposure, or capital allocation implications.
        recommendation: Recommended executive intervention or policy decision.
    """
    clean_title = sanitize_markdown_text(title)
    clean_shows = sanitize_markdown_text(what_it_shows)
    clean_takeaway = sanitize_markdown_text(key_takeaway)
    clean_impact = sanitize_markdown_text(business_impact)

    with st.expander(f"Chart Explanation: {clean_title}", expanded=False):
        st.markdown(
            f"""
            * **What this chart shows**:
              {clean_shows}
            * **The key finding**:
              {clean_takeaway}
            * **Why it matters for the business**:
              {clean_impact}
            """
        )
        if recommendation:
            clean_rec = sanitize_markdown_text(recommendation)
            st.markdown(
                f"""
                * **What should be done about it**:
                  {clean_rec}
                """
            )
